name: GoReleaser

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "24.13.0"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
      - name: build public files
        run: |
          npm install -g pnpm
          echo "清空原有数据"
          rm -rf ui/build
          echo '构建用户页面'
          cd ui && CI=false pnpm install && CI=false pnpm build && cd ..
          echo '构建前端数据完成'
          ls ui/build
          git stash
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
